kumuluzee:
  server:
    http:
      port: 8084
  openapi-mp:
    enabled: true
    scan:
      packages: ec.greeting
    servlet:
      mapping: /public/openapi
    servers: http://localhost:8084
    ui:
      server-auto-config:
        enabled: false #Default: false for production enviroment
        original-uri-check: true
      enabled: true
      mapping: /public/openapi/ui
    scanning:
      debug: true
