# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI / CD DEVOPS Development

on:
  workflow_dispatch:
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  TEST:
    needs: BUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.failure.ignore=true
      - name: Coverage Test
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=true
#      - name: Execute Static Code Analisys with SonarCloud
#        run: mvn sonar:sonar -Dsonar.projectKey=fochoac_devops -Dsonar.organization=fochoac -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.language=java

  DEPLOY_ON_K8S_GKE:
    needs: TEST
    runs-on: ubuntu-latest
    env:
      SHA: ${{github.sha}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    - name: Push Docker Image to Goocle Cloud
      run: mvn clean install -Pgcr -Dregistry=gcr -Denv=dev
    - id: get-cluster-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: devops-cluster-dev
        location: us-central1
        credentials: ${{ secrets.GCR_JSON_KEY }}
    - id: delete-pods
      run: kubectl delete pods --all